//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class easy_chat_utils_api {
  public static readonly int BUFFER_SIZE = easy_chat_utils_apiPINVOKE.BUFFER_SIZE_get();
  public static readonly int SIZE_BYTES = easy_chat_utils_apiPINVOKE.SIZE_BYTES_get();
}
