---
name: "Release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Create Release With Asset
        id: Release-AIO
        uses: Hs1r1us/Release-AIO@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          asset_files: './test.txt'

